/** Per-role visual identity for admin Users & roles — distinct hues, still polished */
export const ROLE_META = {
  admin: {
    label: 'Administrators',
    singular: 'Admin',
    description: 'Users, tasks, grading, system content',
    chip: 'border-secondary/35 bg-white text-secondary shadow-sm ring-1 ring-secondary/15',
    row: 'border-l-[5px] border-l-secondary bg-gradient-to-r from-[#f8fbff] to-white hover:from-[#f0f7ff]',
    header: 'from-secondary via-[#364c6e] to-[#1a2542]',
    dot: 'bg-secondary shadow-sm ring-2 ring-white/90',
    card: 'border border-secondary/20 bg-white shadow-lg shadow-secondary/10 ring-1 ring-secondary/12',
    divide: 'divide-secondary/[0.1]',
    selectRing: 'border-secondary/15 focus:border-secondary/35 focus:ring-2 focus:ring-secondary/25',
    applyBtn: 'bg-secondary text-white shadow-sm hover:bg-[#243652] active:scale-[0.98]',
    pie: '#2d3f5d',
  },
  finance: {
    label: 'Finance',
    singular: 'Finance',
    description: 'Payments, verification, reporting',
    chip: 'border-primary/50 bg-[#fff8ef] text-[#5c3d12] ring-1 ring-primary/25',
    row: 'border-l-[5px] border-l-primary bg-gradient-to-r from-[#fff8ef]/90 to-white hover:from-[#fff4e6]',
    header: 'from-[#faa853] via-[#f59e38] to-[#e89235]',
    dot: 'bg-white shadow ring-2 ring-white/80',
    card: 'border border-primary/35 bg-white shadow-lg shadow-amber-900/10 ring-1 ring-primary/22',
    divide: 'divide-primary/12',
    selectRing: 'border-primary/25 ring-primary/20 focus:border-primary/40 focus:ring-2 focus:ring-primary/30',
    applyBtn: 'bg-primary text-white shadow-sm hover:bg-primary-hover active:scale-[0.98]',
    pie: '#e89235',
  },
  student: {
    label: 'Students',
    singular: 'Student',
    description: 'Course access, assignments, grades',
    chip: 'border-emerald-400/45 bg-emerald-50 text-emerald-950 ring-1 ring-emerald-500/15',
    row: 'border-l-[5px] border-l-emerald-500 bg-gradient-to-r from-emerald-50/80 to-white hover:from-emerald-50',
    header: 'from-emerald-600 via-teal-600 to-teal-800',
    dot: 'bg-emerald-300 shadow ring-2 ring-white/90',
    card: 'border border-emerald-200/90 bg-white shadow-lg shadow-teal-900/8 ring-1 ring-emerald-500/14',
    divide: 'divide-emerald-100/90',
    selectRing: 'border-emerald-200/70 ring-emerald-500/20 focus:border-emerald-400/80 focus:ring-2 focus:ring-emerald-500/25',
    applyBtn: 'bg-emerald-600 text-white shadow-sm hover:bg-emerald-700 active:scale-[0.98]',
    pie: '#0d9488',
  },
  parent: {
    label: 'Parents',
    singular: 'Parent',
    description: 'Child progress, payments, receipts',
    chip: 'border-violet-400/45 bg-violet-50 text-violet-950 ring-1 ring-violet-400/18',
    row: 'border-l-[5px] border-l-violet-500 bg-gradient-to-r from-violet-50/85 to-white hover:from-violet-50',
    header: 'from-violet-600 via-purple-600 to-[#5b21b6]',
    dot: 'bg-violet-300 shadow ring-2 ring-white/90',
    card: 'border border-violet-200/85 bg-white shadow-lg shadow-violet-900/8 ring-1 ring-violet-500/14',
    divide: 'divide-violet-100',
    selectRing: 'border-violet-200/70 ring-violet-500/20 focus:border-violet-400/80 focus:ring-2 focus:ring-violet-500/25',
    applyBtn: 'bg-violet-600 text-white shadow-sm hover:bg-violet-700 active:scale-[0.98]',
    pie: '#7c3aed',
  },
}

export const ROLE_ORDER = ['admin', 'finance', 'student', 'parent']
